spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jiancunqu?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:h2:~/h2/jiancunqu;mv_store=false
#    username: sa
#    password: sa
#    driver-class-name: org.h2.Driver

#    schema: classpath:db/INITSQL.sql
#  flyway:
#    # 如果启动的时候需要flyway管理sql脚本的话，将enabled设置为true
#    enabled: true
#    # 如果数据库不是空表，需要设置成 true，否则启动报错
#    baseline-on-migrate: true
#    # 验证错误时 是否自动清除数据库 高危操作!
#    clean-on-validation-error: false
#
logging:
  level:
    edu.sust.jiancunqu.mapper: debug
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    lazy-loading-enabled: true
  type-aliases-package: edu.sust.jiancunqu.model


server:
  port: 8080
#configure:
#  name: root
#  password: 123456


